name: flutter_ui_flight
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fontfamily/Outfit-SemiBold.ttf
        #       - asset: fonts/Schyler-Italic.ttf
        #         style: italic
    - family: Overpass
      fonts:
        - asset: assets/fontfamily/Overpass-Light.ttf
        #       - asset: fonts/TrajanPro_Bold.ttf
        #         weight: 700
    - family: OverpassMedium
      fonts:
        - asset: assets/fontfamily/Overpass-Medium.ttf

    - family: OverpassSemiBold
      fonts:
        - asset: assets/fontfamily/Overpass-SemiBold.ttf


    - family:  OutfitRegular
      fonts:
        - asset: assets/fontfamily/Outfit-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
